"use client"

import { FormEvent, useEffect, useMemo, useState } from "react"
import { Plus, Check, Trash2, LogOut, Dumbbell, Activity, Footprints, BarChart3, Pencil, MoreHorizontal, X } from "lucide-react"
import { createClient } from "../lib/supabase/client"
import SessionHistory from "../components/SessionHistory"

type Workout={id:string;name:string;description:string|null}
type Exercise={id:string;name:string;muscle_group:string|null;equipment:string|null}
type TE={exercise_id:string;sort_order:number;target_sets:number|null;target_reps_min:number|null;target_reps_max:number|null;exercise:Exercise}
type SetRow={weight:string;reps:string;rpe:string}
type Prev={date:string;sets:{weight:number|null;reps:number|null}[]}
type Cardio={id:string;session_date:string;activity_type:string;duration_seconds:number|null;distance:number|null;distance_unit:string;avg_pace:string|null;avg_heart_rate:number|null;calories:number|null}
type Act={activity_date:string;steps:number|null;distance:number|null;calories:number|null;active_minutes:number|null}
type Point={session_date:string;volume:number;top_weight:number;estimated_1rm:number}
type Tab="strength"|"cardio"|"steps"|"progress"

const supabase=createClient()
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date())
const blank=():SetRow=>({weight:"",reps:"",rpe:""})
const fmt=(s:number|null)=>{if(!s)return "—";const m=Math.floor(s/60),h=Math.floor(m/60);return h?`${h}h ${m%60}m`:`${m}m`}
const fmtDate=(d:string,opts:any)=>new Date(d+"T00:00:00").toLocaleDateString("en-IN",opts)

export default function Home(){
 const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>("strength"),[message,setMessage]=useState(""),[saving,setSaving]=useState(false)
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[authMode,setAuthMode]=useState<"signin"|"signup">("signin"),[authBusy,setAuthBusy]=useState(false)
 const [date,setDate]=useState(today()),[workouts,setWorkouts]=useState<Workout[]>([]),[exercises,setExercises]=useState<Exercise[]>([]),[selectedWorkout,setSelectedWorkout]=useState("")
 const [tes,setTes]=useState<TE[]>([]),[rows,setRows]=useState<Record<string,SetRow[]>>({}),[previous,setPrevious]=useState<Record<string,Prev|null>>({}),[activeSet,setActiveSet]=useState<Record<string,number>>({})
 const [showSetup,setShowSetup]=useState(false),[newWorkout,setNewWorkout]=useState(""),[newExercise,setNewExercise]=useState(""),[newMuscle,setNewMuscle]=useState(""),[editingWorkout,setEditingWorkout]=useState<string|null>(null),[editingWorkoutName,setEditingWorkoutName]=useState(""),[workoutMenu,setWorkoutMenu]=useState<string|null>(null)
 const [cardio,setCardio]=useState<Cardio[]>([]),[cDate,setCDate]=useState(today()),[cType,setCType]=useState("Running"),[cDuration,setCDuration]=useState(""),[cDistance,setCDistance]=useState(""),[cUnit,setCUnit]=useState("km"),[cPace,setCPace]=useState(""),[cHr,setCHr]=useState(""),[cCalories,setCCalories]=useState(""),[cNotes,setCNotes]=useState("")
 const [aDate,setADate]=useState(today()),[steps,setSteps]=useState(""),[target,setTarget]=useState("10000"),[aDistance,setADistance]=useState(""),[aCalories,setACalories]=useState(""),[activeMin,setActiveMin]=useState(""),[activity,setActivity]=useState<Act[]>([])
 const [pExercise,setPExercise]=useState(""),[range,setRange]=useState<"week"|"month"|"year">("month"),[points,setPoints]=useState<Point[]>([]),[pLoading,setPLoading]=useState(false),[sessionCount,setSessionCount]=useState(0)
 const workout=useMemo(()=>workouts.find(w=>w.id===selectedWorkout),[workouts,selectedWorkout])
 const volume=Object.values(rows).flat().reduce((n,r)=>n+(Number(r.weight)||0)*(Number(r.reps)||0),0)

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);setLoading(false)});return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{if(user)loadData()},[user])
 useEffect(()=>{if(selectedWorkout)loadTemplate(selectedWorkout)},[selectedWorkout,date])
 useEffect(()=>{if(user&&tab==="cardio")loadCardio()},[user,tab])
 useEffect(()=>{if(user&&tab==="steps")loadActivity()},[user,tab,aDate])
 useEffect(()=>{if(user&&tab==="progress")loadProgress()},[user,tab,pExercise,range])

 async function loadData(){setLoading(true);const [{data:w},{data:e},{count}]=await Promise.all([supabase.from("workout_templates").select("id,name,description").eq("archived",false).order("created_at"),supabase.from("exercises").select("id,name,muscle_group,equipment").eq("archived",false).order("name"),supabase.from("workout_sessions").select("id",{count:"exact",head:true}).eq("status","completed")]);setWorkouts(w??[]);setExercises(e??[]);setSessionCount(count??0);if(!selectedWorkout&&w?.length)setSelectedWorkout(w[0].id);if(!pExercise&&e?.length)setPExercise(e[0].id);setLoading(false)}
 async function loadTemplate(id:string){const {data}=await supabase.from("workout_template_exercises").select("exercise_id,sort_order,target_sets,target_reps_min,target_reps_max,exercise:exercises(id,name,muscle_group,equipment)").eq("workout_id",id).order("sort_order");const items=(data??[]) as unknown as TE[];setTes(items);const r:Record<string,SetRow[]>={},a:Record<string,number>={};items.forEach(x=>{r[x.exercise_id]=Array.from({length:x.target_sets??3},blank);a[x.exercise_id]=0});setRows(r);setActiveSet(a);await loadPrevious(items.map(x=>x.exercise_id))}
 async function loadPrevious(ids:string[]){if(!ids.length)return;const {data}=await supabase.from("workout_sessions").select("session_date,workout_session_exercises(exercise_id,exercise_sets(weight,reps))").eq("status","completed").lt("session_date",date).order("session_date",{ascending:false}).limit(100);const map:Record<string,Prev|null>={};ids.forEach(id=>map[id]=null);for(const s of(data??[])as any[])for(const se of s.workout_session_exercises??[])if(ids.includes(se.exercise_id)&&!map[se.exercise_id])map[se.exercise_id]={date:s.session_date,sets:se.exercise_sets??[]};setPrevious(map);setRows(old=>{const n={...old};ids.forEach(id=>{const p=map[id];if(p?.sets?.length)n[id]=p.sets.map((s:any)=>({weight:s.weight?.toString()??"",reps:s.reps?.toString()??"",rpe:""}))});return n})}
 function updateSet(id:string,i:number,k:keyof SetRow,v:string){setRows(x=>({...x,[id]:(x[id]??[]).map((r,j)=>j===i?{...r,[k]:v}:r)}))}
 function addSet(id:string){setRows(x=>({...x,[id]:[...(x[id]??[]),blank()]}))}
 function logSet(id:string){const i=activeSet[id]??0,r=rows[id]?.[i];if(!r?.weight||!r?.reps){setMessage("Enter weight and reps before logging the set.");return}setMessage("");setActiveSet(x=>({...x,[id]:Math.min(i+1,(rows[id]??[]).length)}))}
 function editSet(id:string,i:number){setActiveSet(x=>({...x,[id]:i}));setMessage("")}
 async function createWorkout(e:FormEvent){e.preventDefault();if(!newWorkout.trim())return;const {data,error}=await supabase.from("workout_templates").insert({user_id:user.id,name:newWorkout.trim()}).select("id,name,description").single();if(error)return setMessage(error.message);setWorkouts(x=>[...x,data]);setNewWorkout("");setShowSetup(false);setWorkoutMenu(null);setMessage("Workout created. Your current workout and logged sets are unchanged.")}
 async function renameWorkout(id:string){const name=editingWorkoutName.trim();if(!name)return;const {data,error}=await supabase.from("workout_templates").update({name}).eq("id",id).select("id,name,description").single();if(error)return setMessage(error.message);setWorkouts(x=>x.map(w=>w.id===id?data:w));setEditingWorkout(null);setWorkoutMenu(null);setMessage("")}
 async function deleteWorkout(id:string){const targetWorkout=workouts.find(w=>w.id===id);if(!targetWorkout)return;if(!window.confirm(`Delete “${targetWorkout.name}”? It will be removed from your workout list; completed history is kept.`))return;const {error}=await supabase.from("workout_templates").update({archived:true}).eq("id",id);if(error)return setMessage(error.message);const remaining=workouts.filter(w=>w.id!==id);setWorkouts(remaining);setWorkoutMenu(null);if(selectedWorkout===id)setSelectedWorkout(remaining[0]?.id??"");setMessage("")}
 async function createExercise(e:FormEvent){e.preventDefault();if(!newExercise.trim())return;const {data,error}=await supabase.from("exercises").insert({user_id:user.id,name:newExercise.trim(),muscle_group:newMuscle.trim()||null}).select("id,name,muscle_group,equipment").single();if(error)return setMessage(error.message);setExercises(x=>[...x,data].sort((a,b)=>a.name.localeCompare(b.name)));setNewExercise("");setNewMuscle("")}
 async function addExercise(id:string){if(!selectedWorkout||tes.some(x=>x.exercise_id===id))return;const {error}=await supabase.from("workout_template_exercises").insert({workout_id:selectedWorkout,exercise_id:id,sort_order:tes.length,target_sets:3,target_reps_min:8,target_reps_max:12});if(error)setMessage(error.message);else loadTemplate(selectedWorkout)}
 async function finishWorkout(){if(!selectedWorkout||!tes.length)return setMessage("Choose a workout with at least one exercise.");if(!Object.values(rows).some(rs=>rs.some(r=>r.weight||r.reps)))return setMessage("Log at least one set before finishing.");setSaving(true);const payload={workout_id:selectedWorkout,workout_name:workout?.name,session_date:date,started_at:new Date().toISOString(),exercises:tes.map(x=>({exercise_id:x.exercise_id,exercise_name:x.exercise.name,sets:(rows[x.exercise_id]??[]).map((r,i)=>({set_number:i+1,weight:r.weight||null,reps:r.reps||null,rpe:r.rpe||null,completed:Boolean(r.weight||r.reps)}))}))};const {error}=await supabase.rpc("finish_workout",{payload});setMessage(error?error.message:"Workout saved ✓ — open Saved sessions below to review it.");if(!error){await loadData();await loadTemplate(selectedWorkout)}setSaving(false)}
 async function auth(e:FormEvent){e.preventDefault();setAuthBusy(true);const r=authMode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setMessage(r.error.message);else setMessage(authMode==="signup"?"Account created. Check your email if confirmation is enabled.":"");setAuthBusy(false)}
 async function loadCardio(){const {data}=await supabase.from("cardio_sessions").select("id,session_date,activity_type,duration_seconds,distance,distance_unit,avg_pace,avg_heart_rate,calories").order("session_date",{ascending:false}).limit(20);setCardio(data??[])}
 async function saveCardio(e:FormEvent){e.preventDefault();setSaving(true);const {error}=await supabase.from("cardio_sessions").insert({user_id:user.id,session_date:cDate,activity_type:cType,duration_seconds:cDuration?Number(cDuration)*60:null,distance:cDistance?Number(cDistance):null,distance_unit:cUnit,avg_pace:cPace||null,avg_heart_rate:cHr?Number(cHr):null,calories:cCalories?Number(cCalories):null,notes:cNotes||null});setMessage(error?error.message:"Cardio session saved ✓");if(!error){setCDuration("");setCDistance("");setCPace("");setCHr("");setCCalories("");setCNotes("");await loadCardio()}setSaving(false)}
 async function loadActivity(){const {data}=await supabase.from("daily_activity").select("activity_date,steps,distance,calories,active_minutes").order("activity_date",{ascending:false}).limit(14);setActivity(data??[]);const cur=(data??[]).find(x=>x.activity_date===aDate);if(cur){setSteps(cur.steps?.toString()??"");setADistance(cur.distance?.toString()??"");setACalories(cur.calories?.toString()??"");setActiveMin(cur.active_minutes?.toString()??"")}}
 async function saveActivity(e:FormEvent){e.preventDefault();setSaving(true);const {error}=await supabase.from("daily_activity").upsert({user_id:user.id,activity_date:aDate,steps:steps?Number(steps):null,distance:aDistance?Number(aDistance):null,calories:aCalories?Number(aCalories):null,active_minutes:activeMin?Number(activeMin):null});setMessage(error?error.message:"Daily activity saved ✓");if(!error)await loadActivity();setSaving(false)}
 async function loadProgress(){if(!pExercise)return;setPLoading(true);const days=range==="week"?7:range==="month"?30:365,d=new Date();d.setDate(d.getDate()-days);const since=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(d);const {data}=await supabase.from("exercise_progress").select("session_date,volume,top_weight,estimated_1rm").eq("exercise_id",pExercise).gte("session_date",since).order("session_date");setPoints((data??[])as Point[]);setPLoading(false)}

 if(loading)return <main className="shell loading"><div className="spinner"/>Loading your tracker…</main>
 if(!user)return <main className="authShell"><div className="authCard"><div className="logoMark"><Dumbbell size={22}/></div><h1>Fitness Tracker</h1><p className="muted">Your training, one clean log.</p><div className="authTabs"><button className={authMode==="signin"?"active":""} onClick={()=>setAuthMode("signin")}>Sign in</button><button className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>Create account</button></div><form onSubmit={auth} className="formStack"><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password (6+ characters)" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/><button className="btn primary wide" disabled={authBusy}>{authBusy?"Please wait…":authMode==="signin"?"Sign in":"Create account"}</button></form>{message&&<div className="notice error">{message}</div>}</div></main>
 const nav=(t:Tab)=>{setTab(t);setMessage("")}
 const pMax=Math.max(1,...points.map(p=>Number(p.volume)||0)),latest=points[points.length-1],first=points[0],change=first&&latest?((Number(latest.volume)-Number(first.volume))/Math.max(1,Number(first.volume)))*100:0,pct=Math.min(100,Number(steps)/Math.max(1,Number(target))*100)
 return <main className="shell"><header className="top"><div><div className="brand">Fitness Tracker</div><div className="muted">Train. Track. Progress.</div></div><div className="nav"><button className={`pill ${tab==="strength"?"activePill":""}`} onClick={()=>nav("strength")}><Dumbbell size={14}/> Strength</button><button className={`pill ${tab==="cardio"?"activePill":""}`} onClick={()=>nav("cardio")}><Activity size={14}/> Cardio</button><button className={`pill ${tab==="steps"?"activePill":""}`} onClick={()=>nav("steps")}><Footprints size={14}/> Steps</button><button className={`pill ${tab==="progress"?"activePill":""}`} onClick={()=>nav("progress")}><BarChart3 size={14}/> Progress</button><button className="iconBtn" onClick={()=>supabase.auth.signOut()} aria-label="Sign out"><LogOut size={17}/></button></div></header>
 {tab==="strength"&&<><section className="hero"><div><div className="eyebrow">{date===today()?"TODAY":date}</div><h1>{workout?.name??"Start your training"}</h1><p>Log one set, then move straight to the next.</p></div><button className="btn primary finish" onClick={finishWorkout} disabled={saving}>{saving?"Saving…":<><Check size={17}/> Finish Workout</>}</button></section>
 <section className="grid stats"><div className="card"><div className="muted">Exercises</div><div className="stat">{tes.length}</div><div className="muted">in session</div></div><div className="card"><div className="muted">Volume</div><div className="stat">{Math.round(volume).toLocaleString()} kg</div><div className="muted">entered</div></div><div className="card"><div className="muted">Sessions</div><div className="stat">{sessionCount}</div><div className="muted">completed</div></div><div className="card insightCard"><div className="muted">Next-session benchmark</div><strong>Previous performance</strong><div className="muted">is prefilled.</div></div></section>
 <section className="card controls"><div className="controlGroup"><label>DATE</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="controlGroup workoutPicker"><label>WORKOUT</label><div className="chipRow">{workouts.map(w=><div key={w.id} className="workoutChipWrap"><button className={`chip ${selectedWorkout===w.id?"selected":""}`} onClick={()=>{setSelectedWorkout(w.id);setWorkoutMenu(null)}}>{editingWorkout===w.id?<input autoFocus value={editingWorkoutName} onChange={e=>setEditingWorkoutName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")renameWorkout(w.id);if(e.key==="Escape")setEditingWorkout(null)}} onClick={e=>e.stopPropagation()}/>:w.name}</button><button className="workoutMenuBtn" onClick={e=>{e.stopPropagation();setWorkoutMenu(workoutMenu===w.id?null:w.id)}} aria-label={`Manage ${w.name}`}><MoreHorizontal size={15}/></button>{workoutMenu===w.id&&<div className="workoutMenu"><button onClick={()=>{setEditingWorkout(w.id);setEditingWorkoutName(w.name);setWorkoutMenu(null)}}><Pencil size={14}/> Rename</button><button className="dangerAction" onClick={()=>deleteWorkout(w.id)}><Trash2 size={14}/> Delete</button></div>}</div>)}<button className="chip add" onClick={()=>{setShowSetup(v=>!v);setWorkoutMenu(null)}}><Plus size={14}/> Manage</button></div></div></section>
 {showSetup&&<section className="card setupGrid"><div><h3>Add workout</h3><form className="inlineForm" onSubmit={createWorkout}><input placeholder="e.g. Push Day" value={newWorkout} onChange={e=>setNewWorkout(e.target.value)}/><button className="btn primary" type="submit"><Plus size={15}/> Add</button></form><p className="muted setupHint">Adding a workout no longer changes the active workout or clears your current logged sets.</p></div><div><h3>Add exercise</h3><form className="inlineForm" onSubmit={createExercise}><input placeholder="Exercise name" value={newExercise} onChange={e=>setNewExercise(e.target.value)}/><input placeholder="Muscle" value={newMuscle} onChange={e=>setNewMuscle(e.target.value)}/><button className="btn primary" type="submit"><Plus size={15}/> Add</button></form><div className="exercisePool">{exercises.filter(e=>!tes.some(x=>x.exercise_id===e.id)).slice(0,10).map(e=><button className="poolItem" key={e.id} onClick={()=>addExercise(e.id)}>{e.name}<span><Plus size={13}/></span></button>)}</div></div></section>}
 <section className="card workoutCard"><div className="sectionHead"><div><h2>Log workout</h2><p className="muted">Enter weight and reps, tap Log set & next, and keep moving.</p></div><div className="statBadge">{tes.reduce((n,x)=>n+Math.min(activeSet[x.exercise_id]??0,(rows[x.exercise_id]??[]).length),0)} sets logged</div></div><div className="exerciseList">{tes.length===0?<div className="empty"><Dumbbell size={24}/><strong>No exercises yet</strong><span>Add an exercise from Manage to build this workout.</span></div>:tes.map(x=>{const rs=rows[x.exercise_id]??[];const ai=activeSet[x.exercise_id]??0;const logged=Math.min(ai,rs.length);const done=logged>=rs.length;const prev=previous[x.exercise_id];return <div className="exercise" key={x.exercise_id}><div className="exerciseHeader"><div><h3>{x.exercise.name}</h3><p className="muted">{x.exercise.muscle_group||"Strength"} · {x.target_reps_min??8}–{x.target_reps_max??12} reps</p></div>{prev&&<div className="previous"><span>Previous · {fmtDate(prev.date,{day:"numeric",month:"short"})}</span><strong>{prev.sets.map(s=>`${s.weight??"—"} × ${s.reps??"—"}`).join(" · ")}</strong></div>}</div><div className="setTable">{done?<div className="exerciseDone"><Check size={18}/><div><strong>Exercise complete</strong><span>{logged} sets logged</span></div></div>:<><div className="setProgress">Set {Math.min(ai+1,rs.length)} of {rs.length}<span>{logged} logged</span></div>{rs.slice(0,ai+1).map((r,i)=>i<ai?<div className="loggedSet" key={i}><span className="setNo">{i+1}</span><strong>{r.weight} kg × {r.reps}</strong>{r.rpe&&<span>RPE {r.rpe}</span>}<button className="editSetBtn" onClick={()=>editSet(x.exercise_id,i)}><Pencil size={13}/> Edit</button></div>:null)}<div className="workingSet"><div className="workingSetLabel"><span className="setNo">{ai+1}</span><div><strong>Working set</strong><span>Enter this set</span></div></div><div className="workingInputs"><input inputMode="decimal" placeholder="Weight (kg)" value={rs[ai]?.weight??""} onChange={e=>updateSet(x.exercise_id,ai,"weight",e.target.value)}/><input inputMode="numeric" placeholder="Reps" value={rs[ai]?.reps??""} onChange={e=>updateSet(x.exercise_id,ai,"reps",e.target.value)}/><input inputMode="decimal" placeholder="RPE" value={rs[ai]?.rpe??""} onChange={e=>updateSet(x.exercise_id,ai,"rpe",e.target.value)}/></div><button className="btn primary logNext" onClick={()=>logSet(x.exercise_id)}><Check size={15}/> {ai+1<rs.length?"Log set & next":"Log final set"}</button></div><button className="addSet" onClick={()=>addSet(x.exercise_id)}><Plus size={14}/> Add another set</button></>}</div></div>})}</div></section>
 <SessionHistory/>{message&&<div className="notice">{message}</div>}</>}
 {tab==="cardio"&&<section className="pageSection"><div className="pageIntro"><div><div className="eyebrow">CARDIO</div><h1>Cardio</h1><p className="muted">Log runs, cycling, rowing and other conditioning sessions.</p></div></div><div className="twoCol"><form className="card formCard" onSubmit={saveCardio}><h2>Log session</h2><div className="formGrid"><label>Date<input type="date" value={cDate} onChange={e=>setCDate(e.target.value)}/></label><label>Activity<input value={cType} onChange={e=>setCType(e.target.value)} placeholder="Running"/></label><label>Duration (min)<input inputMode="numeric" value={cDuration} onChange={e=>setCDuration(e.target.value)}/></label><label>Distance<input inputMode="decimal" value={cDistance} onChange={e=>setCDistance(e.target.value)}/></label><label>Unit<select value={cUnit} onChange={e=>setCUnit(e.target.value)}><option>km</option><option>mi</option></select></label><label>Avg pace<input value={cPace} onChange={e=>setCPace(e.target.value)} placeholder="5:30 / km"/></label><label>Avg HR<input inputMode="numeric" value={cHr} onChange={e=>setCHr(e.target.value)}/></label><label>Calories<input inputMode="numeric" value={cCalories} onChange={e=>setCCalories(e.target.value)}/></label></div><label>Notes<textarea value={cNotes} onChange={e=>setCNotes(e.target.value)} /></label><button className="btn primary" disabled={saving}>Save cardio session</button></form><section className="card historyCard"><h2>Recent cardio</h2><div className="historyList">{cardio.map(c=><div className="historyItem" key={c.id}><div><strong>{c.activity_type}</strong><span>{fmtDate(c.session_date,{day:"numeric",month:"short",year:"numeric"})}</span></div><div className="historyMetrics"><b>{fmt(c.duration_seconds)}</b>{c.distance&&<b>{c.distance} {c.distance_unit}</b>}{c.calories&&<b>{c.calories} kcal</b>}</div></div>)}{!cardio.length&&<div className="empty small">No cardio sessions yet.</div>}</div></section></div></section>}
 {tab==="steps"&&<section className="pageSection"><div className="pageIntro"><div><div className="eyebrow">DAILY ACTIVITY</div><h1>Steps</h1><p className="muted">Keep your daily movement visible alongside training.</p></div></div><div className="twoCol"><form className="card formCard" onSubmit={saveActivity}><h2>Daily activity</h2><div className="formGrid"><label>Date<input type="date" value={aDate} onChange={e=>setADate(e.target.value)}/></label><label>Steps<input inputMode="numeric" value={steps} onChange={e=>setSteps(e.target.value)}/></label><label>Target<input inputMode="numeric" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Distance (km)<input inputMode="decimal" value={aDistance} onChange={e=>setADistance(e.target.value)}/></label><label>Calories<input inputMode="numeric" value={aCalories} onChange={e=>setACalories(e.target.value)}/></label><label>Active minutes<input inputMode="numeric" value={activeMin} onChange={e=>setActiveMin(e.target.value)}/></label></div><div className="goal"><div className="sectionHead"><strong>{Number(steps||0).toLocaleString()} / {Number(target||0).toLocaleString()} steps</strong><span className="muted">{Math.round(pct)}%</span></div><div className="progressBar"><span style={{width:`${pct}%`}}/></div></div><button className="btn primary" disabled={saving}>Save activity</button></form><section className="card historyCard"><h2>Recent days</h2><div className="historyList">{activity.map(a=><div className="historyItem" key={a.activity_date}><div><strong>{Number(a.steps||0).toLocaleString()} steps</strong><span>{fmtDate(a.activity_date,{day:"numeric",month:"short"})}</span></div><div className="historyMetrics">{a.distance&&<b>{a.distance} km</b>}{a.active_minutes&&<b>{a.active_minutes} min</b>}</div></div>)}{!activity.length&&<div className="empty small">No activity logged yet.</div>}</div></section></div></section>}
 {tab==="progress"&&<section className="pageSection"><div className="pageIntro"><div><div className="eyebrow">PROGRESS</div><h1>Progress</h1><p className="muted">See how your training volume and strength trend over time.</p></div></div><section className="card"><div className="progressControls"><label>EXERCISE<select value={pExercise} onChange={e=>setPExercise(e.target.value)}>{exercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="rangeToggle">{(["week","month","year"] as const).map(r=><button key={r} className={range===r?"selected":""} onClick={()=>setRange(r)}>{r[0].toUpperCase()+r.slice(1)}</button>)}</div></div>{pLoading?<div className="empty small">Loading progress…</div>:<><div className="progressSummary"><div><span className="muted">Sessions</span><strong>{points.length}</strong></div><div><span className="muted">Latest volume</span><strong>{latest?`${Math.round(latest.volume).toLocaleString()} kg`:"—"}</strong></div><div><span className="muted">Change</span><strong className={change>=0?"positive":"negative"}>{points.length>1?`${change>=0?"+":""}${change.toFixed(0)}%`:"—"}</strong></div></div><div className="chartWrap"><div className="chartBars">{points.length?points.map((p,i)=><div className="barColumn" key={`${p.session_date}-${i}`}><span>{fmtDate(p.session_date,{day:"numeric",month:"short"})}</span><div className="bar" style={{height:`${Math.max(3,(Number(p.volume)/pMax)*100)}%`}}/><span className="barValue">{Math.round(p.volume).toLocaleString()}</span></div>):<div className="empty small">Complete a workout to start seeing progress.</div>}</div></div></>}</section></section>}
 </main>
}
